create table "public"."aslab" (
    "id_aslab" uuid not null default gen_random_uuid(),
    "nama" text not null,
    "nim" text not null,
    "email" text not null,
    "no_hp" character varying(15),
    "angkatan" character varying(4),
    "program_studi" text not null,
    "status" character varying(20) not null,
    "profile_picture" text,
    "pendidikan_terakhir" text
);


create table "public"."aslab_honor" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "aslab" uuid,
    "tahun_semester" bigint,
    "status_honor" text,
    "tanggal_diambil" date
);


create table "public"."dosen_pengampu" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "nama" text,
    "nip" text,
    "email" text,
    "slug" text
);


create table "public"."honor_jenis" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "jenis" text,
    "biaya" bigint,
    "slug" text
);


create table "public"."kalab" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "nama" text,
    "nip" text,
    "email" text,
    "no_hp" text,
    "photo" text,
    "slug" text not null
);


create table "public"."kelas_aslab" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "aslab" uuid not null,
    "kelas" bigint not null
);


create table "public"."kelas_praktikum" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "kelas" text,
    "mata_kuliah" bigint,
    "id_dosen" bigint,
    "jumlah_praktikan" bigint,
    "hari" text,
    "lab" bigint,
    "jenis_praktikan" text,
    "waktu" text,
    "slug" text,
    "tahun_semester" bigint
);


create table "public"."lab" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "nama" text,
    "lantai" text,
    "kapasitas" bigint,
    "kalab" bigint,
    "slug" text not null
);


create table "public"."mata_kuliah_praktikum" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "nama" text not null,
    "semester" text,
    "jumlah_kelas" bigint default '0'::bigint,
    "slug" text not null,
    "kode_mk" integer not null
);


create table "public"."permintaan_sertifikat" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "id_aslab" uuid,
    "waktu_pengajuan" timestamp with time zone,
    "status" text default 'pending'::text,
    "keterangan" text
);


create table "public"."profiles" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "nama" text,
    "role" text,
    "aslab_id" uuid,
    "email" text,
    "slug" text
);


create table "public"."tahun_semester" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "semester" text,
    "tahun_ajaran" text,
    "slug" text
);


create table "public"."test" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text
);


CREATE UNIQUE INDEX aslab_email_key ON public.aslab USING btree (email);

CREATE UNIQUE INDEX aslab_honor_pkey ON public.aslab_honor USING btree (id);

CREATE UNIQUE INDEX aslab_nim_key ON public.aslab USING btree (nim);

CREATE UNIQUE INDEX aslab_pkey ON public.aslab USING btree (id_aslab);

CREATE UNIQUE INDEX dosen_pengampu_pkey ON public.dosen_pengampu USING btree (id);

CREATE UNIQUE INDEX honor_jenis_jenis_key ON public.honor_jenis USING btree (jenis);

CREATE UNIQUE INDEX honor_jenis_pkey ON public.honor_jenis USING btree (id);

CREATE UNIQUE INDEX kalab_pkey ON public.kalab USING btree (id);

CREATE UNIQUE INDEX kalab_slug_key ON public.kalab USING btree (slug);

CREATE UNIQUE INDEX kelas_aslab_pkey ON public.kelas_aslab USING btree (id);

CREATE UNIQUE INDEX kelas_praktikum_pkey ON public.kelas_praktikum USING btree (id);

CREATE UNIQUE INDEX lab_pkey ON public.lab USING btree (id);

CREATE UNIQUE INDEX lab_slug_key ON public.lab USING btree (slug);

CREATE UNIQUE INDEX mata_kuliah_praktikum_kode_mk_key ON public.mata_kuliah_praktikum USING btree (kode_mk);

CREATE UNIQUE INDEX mata_kuliah_praktikum_nama_key ON public.mata_kuliah_praktikum USING btree (nama);

CREATE UNIQUE INDEX mata_kuliah_praktikum_pkey ON public.mata_kuliah_praktikum USING btree (id);

CREATE UNIQUE INDEX mata_kuliah_praktikum_slug_key ON public.mata_kuliah_praktikum USING btree (slug);

CREATE UNIQUE INDEX permintaan_sertifikat_pkey ON public.permintaan_sertifikat USING btree (id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX tahun_semester_pkey ON public.tahun_semester USING btree (id);

CREATE UNIQUE INDEX tahun_semester_slug_key ON public.tahun_semester USING btree (slug);

CREATE UNIQUE INDEX test_pkey ON public.test USING btree (id);

alter table "public"."aslab" add constraint "aslab_pkey" PRIMARY KEY using index "aslab_pkey";

alter table "public"."aslab_honor" add constraint "aslab_honor_pkey" PRIMARY KEY using index "aslab_honor_pkey";

alter table "public"."dosen_pengampu" add constraint "dosen_pengampu_pkey" PRIMARY KEY using index "dosen_pengampu_pkey";

alter table "public"."honor_jenis" add constraint "honor_jenis_pkey" PRIMARY KEY using index "honor_jenis_pkey";

alter table "public"."kalab" add constraint "kalab_pkey" PRIMARY KEY using index "kalab_pkey";

alter table "public"."kelas_aslab" add constraint "kelas_aslab_pkey" PRIMARY KEY using index "kelas_aslab_pkey";

alter table "public"."kelas_praktikum" add constraint "kelas_praktikum_pkey" PRIMARY KEY using index "kelas_praktikum_pkey";

alter table "public"."lab" add constraint "lab_pkey" PRIMARY KEY using index "lab_pkey";

alter table "public"."mata_kuliah_praktikum" add constraint "mata_kuliah_praktikum_pkey" PRIMARY KEY using index "mata_kuliah_praktikum_pkey";

alter table "public"."permintaan_sertifikat" add constraint "permintaan_sertifikat_pkey" PRIMARY KEY using index "permintaan_sertifikat_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."tahun_semester" add constraint "tahun_semester_pkey" PRIMARY KEY using index "tahun_semester_pkey";

alter table "public"."test" add constraint "test_pkey" PRIMARY KEY using index "test_pkey";

alter table "public"."aslab" add constraint "aslab_email_key" UNIQUE using index "aslab_email_key";

alter table "public"."aslab" add constraint "aslab_nim_key" UNIQUE using index "aslab_nim_key";

alter table "public"."aslab" add constraint "aslab_status_check" CHECK (((status)::text = ANY (ARRAY[('Aktif'::character varying)::text, ('Tidak Aktif'::character varying)::text]))) not valid;

alter table "public"."aslab" validate constraint "aslab_status_check";

alter table "public"."aslab_honor" add constraint "aslab_honor_aslab_fkey" FOREIGN KEY (aslab) REFERENCES aslab(id_aslab) not valid;

alter table "public"."aslab_honor" validate constraint "aslab_honor_aslab_fkey";

alter table "public"."aslab_honor" add constraint "aslab_honor_tahun_semester_fkey" FOREIGN KEY (tahun_semester) REFERENCES tahun_semester(id) ON DELETE SET NULL not valid;

alter table "public"."aslab_honor" validate constraint "aslab_honor_tahun_semester_fkey";

alter table "public"."honor_jenis" add constraint "honor_jenis_jenis_key" UNIQUE using index "honor_jenis_jenis_key";

alter table "public"."kalab" add constraint "kalab_slug_key" UNIQUE using index "kalab_slug_key";

alter table "public"."kelas_aslab" add constraint "kelas_aslab_aslab_fkey" FOREIGN KEY (aslab) REFERENCES aslab(id_aslab) ON DELETE CASCADE not valid;

alter table "public"."kelas_aslab" validate constraint "kelas_aslab_aslab_fkey";

alter table "public"."kelas_aslab" add constraint "kelas_aslab_kelas_fkey" FOREIGN KEY (kelas) REFERENCES kelas_praktikum(id) ON DELETE CASCADE not valid;

alter table "public"."kelas_aslab" validate constraint "kelas_aslab_kelas_fkey";

alter table "public"."kelas_praktikum" add constraint "kelas_praktikum_id_dosen_fkey" FOREIGN KEY (id_dosen) REFERENCES dosen_pengampu(id) not valid;

alter table "public"."kelas_praktikum" validate constraint "kelas_praktikum_id_dosen_fkey";

alter table "public"."kelas_praktikum" add constraint "kelas_praktikum_lab_fkey" FOREIGN KEY (lab) REFERENCES lab(id) not valid;

alter table "public"."kelas_praktikum" validate constraint "kelas_praktikum_lab_fkey";

alter table "public"."kelas_praktikum" add constraint "kelas_praktikum_mata_kuliah_fkey" FOREIGN KEY (mata_kuliah) REFERENCES mata_kuliah_praktikum(id) not valid;

alter table "public"."kelas_praktikum" validate constraint "kelas_praktikum_mata_kuliah_fkey";

alter table "public"."kelas_praktikum" add constraint "kelas_praktikum_tahun_semester_fkey" FOREIGN KEY (tahun_semester) REFERENCES tahun_semester(id) not valid;

alter table "public"."kelas_praktikum" validate constraint "kelas_praktikum_tahun_semester_fkey";

alter table "public"."lab" add constraint "lab_kalab_fkey" FOREIGN KEY (kalab) REFERENCES kalab(id) not valid;

alter table "public"."lab" validate constraint "lab_kalab_fkey";

alter table "public"."lab" add constraint "lab_slug_key" UNIQUE using index "lab_slug_key";

alter table "public"."mata_kuliah_praktikum" add constraint "mata_kuliah_praktikum_kode_mk_key" UNIQUE using index "mata_kuliah_praktikum_kode_mk_key";

alter table "public"."mata_kuliah_praktikum" add constraint "mata_kuliah_praktikum_nama_key" UNIQUE using index "mata_kuliah_praktikum_nama_key";

alter table "public"."mata_kuliah_praktikum" add constraint "mata_kuliah_praktikum_slug_key" UNIQUE using index "mata_kuliah_praktikum_slug_key";

alter table "public"."permintaan_sertifikat" add constraint "permintaan_sertifikat_id_aslab_fkey" FOREIGN KEY (id_aslab) REFERENCES aslab(id_aslab) not valid;

alter table "public"."permintaan_sertifikat" validate constraint "permintaan_sertifikat_id_aslab_fkey";

alter table "public"."profiles" add constraint "profiles_aslab_id_fkey" FOREIGN KEY (aslab_id) REFERENCES aslab(id_aslab) ON UPDATE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_aslab_id_fkey";

alter table "public"."tahun_semester" add constraint "tahun_semester_slug_key" UNIQUE using index "tahun_semester_slug_key";

grant delete on table "public"."aslab" to "anon";

grant insert on table "public"."aslab" to "anon";

grant references on table "public"."aslab" to "anon";

grant select on table "public"."aslab" to "anon";

grant trigger on table "public"."aslab" to "anon";

grant truncate on table "public"."aslab" to "anon";

grant update on table "public"."aslab" to "anon";

grant delete on table "public"."aslab" to "authenticated";

grant insert on table "public"."aslab" to "authenticated";

grant references on table "public"."aslab" to "authenticated";

grant select on table "public"."aslab" to "authenticated";

grant trigger on table "public"."aslab" to "authenticated";

grant truncate on table "public"."aslab" to "authenticated";

grant update on table "public"."aslab" to "authenticated";

grant delete on table "public"."aslab" to "service_role";

grant insert on table "public"."aslab" to "service_role";

grant references on table "public"."aslab" to "service_role";

grant select on table "public"."aslab" to "service_role";

grant trigger on table "public"."aslab" to "service_role";

grant truncate on table "public"."aslab" to "service_role";

grant update on table "public"."aslab" to "service_role";

grant delete on table "public"."aslab_honor" to "anon";

grant insert on table "public"."aslab_honor" to "anon";

grant references on table "public"."aslab_honor" to "anon";

grant select on table "public"."aslab_honor" to "anon";

grant trigger on table "public"."aslab_honor" to "anon";

grant truncate on table "public"."aslab_honor" to "anon";

grant update on table "public"."aslab_honor" to "anon";

grant delete on table "public"."aslab_honor" to "authenticated";

grant insert on table "public"."aslab_honor" to "authenticated";

grant references on table "public"."aslab_honor" to "authenticated";

grant select on table "public"."aslab_honor" to "authenticated";

grant trigger on table "public"."aslab_honor" to "authenticated";

grant truncate on table "public"."aslab_honor" to "authenticated";

grant update on table "public"."aslab_honor" to "authenticated";

grant delete on table "public"."aslab_honor" to "service_role";

grant insert on table "public"."aslab_honor" to "service_role";

grant references on table "public"."aslab_honor" to "service_role";

grant select on table "public"."aslab_honor" to "service_role";

grant trigger on table "public"."aslab_honor" to "service_role";

grant truncate on table "public"."aslab_honor" to "service_role";

grant update on table "public"."aslab_honor" to "service_role";

grant delete on table "public"."dosen_pengampu" to "anon";

grant insert on table "public"."dosen_pengampu" to "anon";

grant references on table "public"."dosen_pengampu" to "anon";

grant select on table "public"."dosen_pengampu" to "anon";

grant trigger on table "public"."dosen_pengampu" to "anon";

grant truncate on table "public"."dosen_pengampu" to "anon";

grant update on table "public"."dosen_pengampu" to "anon";

grant delete on table "public"."dosen_pengampu" to "authenticated";

grant insert on table "public"."dosen_pengampu" to "authenticated";

grant references on table "public"."dosen_pengampu" to "authenticated";

grant select on table "public"."dosen_pengampu" to "authenticated";

grant trigger on table "public"."dosen_pengampu" to "authenticated";

grant truncate on table "public"."dosen_pengampu" to "authenticated";

grant update on table "public"."dosen_pengampu" to "authenticated";

grant delete on table "public"."dosen_pengampu" to "service_role";

grant insert on table "public"."dosen_pengampu" to "service_role";

grant references on table "public"."dosen_pengampu" to "service_role";

grant select on table "public"."dosen_pengampu" to "service_role";

grant trigger on table "public"."dosen_pengampu" to "service_role";

grant truncate on table "public"."dosen_pengampu" to "service_role";

grant update on table "public"."dosen_pengampu" to "service_role";

grant delete on table "public"."honor_jenis" to "anon";

grant insert on table "public"."honor_jenis" to "anon";

grant references on table "public"."honor_jenis" to "anon";

grant select on table "public"."honor_jenis" to "anon";

grant trigger on table "public"."honor_jenis" to "anon";

grant truncate on table "public"."honor_jenis" to "anon";

grant update on table "public"."honor_jenis" to "anon";

grant delete on table "public"."honor_jenis" to "authenticated";

grant insert on table "public"."honor_jenis" to "authenticated";

grant references on table "public"."honor_jenis" to "authenticated";

grant select on table "public"."honor_jenis" to "authenticated";

grant trigger on table "public"."honor_jenis" to "authenticated";

grant truncate on table "public"."honor_jenis" to "authenticated";

grant update on table "public"."honor_jenis" to "authenticated";

grant delete on table "public"."honor_jenis" to "service_role";

grant insert on table "public"."honor_jenis" to "service_role";

grant references on table "public"."honor_jenis" to "service_role";

grant select on table "public"."honor_jenis" to "service_role";

grant trigger on table "public"."honor_jenis" to "service_role";

grant truncate on table "public"."honor_jenis" to "service_role";

grant update on table "public"."honor_jenis" to "service_role";

grant delete on table "public"."kalab" to "anon";

grant insert on table "public"."kalab" to "anon";

grant references on table "public"."kalab" to "anon";

grant select on table "public"."kalab" to "anon";

grant trigger on table "public"."kalab" to "anon";

grant truncate on table "public"."kalab" to "anon";

grant update on table "public"."kalab" to "anon";

grant delete on table "public"."kalab" to "authenticated";

grant insert on table "public"."kalab" to "authenticated";

grant references on table "public"."kalab" to "authenticated";

grant select on table "public"."kalab" to "authenticated";

grant trigger on table "public"."kalab" to "authenticated";

grant truncate on table "public"."kalab" to "authenticated";

grant update on table "public"."kalab" to "authenticated";

grant delete on table "public"."kalab" to "service_role";

grant insert on table "public"."kalab" to "service_role";

grant references on table "public"."kalab" to "service_role";

grant select on table "public"."kalab" to "service_role";

grant trigger on table "public"."kalab" to "service_role";

grant truncate on table "public"."kalab" to "service_role";

grant update on table "public"."kalab" to "service_role";

grant delete on table "public"."kelas_aslab" to "anon";

grant insert on table "public"."kelas_aslab" to "anon";

grant references on table "public"."kelas_aslab" to "anon";

grant select on table "public"."kelas_aslab" to "anon";

grant trigger on table "public"."kelas_aslab" to "anon";

grant truncate on table "public"."kelas_aslab" to "anon";

grant update on table "public"."kelas_aslab" to "anon";

grant delete on table "public"."kelas_aslab" to "authenticated";

grant insert on table "public"."kelas_aslab" to "authenticated";

grant references on table "public"."kelas_aslab" to "authenticated";

grant select on table "public"."kelas_aslab" to "authenticated";

grant trigger on table "public"."kelas_aslab" to "authenticated";

grant truncate on table "public"."kelas_aslab" to "authenticated";

grant update on table "public"."kelas_aslab" to "authenticated";

grant delete on table "public"."kelas_aslab" to "service_role";

grant insert on table "public"."kelas_aslab" to "service_role";

grant references on table "public"."kelas_aslab" to "service_role";

grant select on table "public"."kelas_aslab" to "service_role";

grant trigger on table "public"."kelas_aslab" to "service_role";

grant truncate on table "public"."kelas_aslab" to "service_role";

grant update on table "public"."kelas_aslab" to "service_role";

grant delete on table "public"."kelas_praktikum" to "anon";

grant insert on table "public"."kelas_praktikum" to "anon";

grant references on table "public"."kelas_praktikum" to "anon";

grant select on table "public"."kelas_praktikum" to "anon";

grant trigger on table "public"."kelas_praktikum" to "anon";

grant truncate on table "public"."kelas_praktikum" to "anon";

grant update on table "public"."kelas_praktikum" to "anon";

grant delete on table "public"."kelas_praktikum" to "authenticated";

grant insert on table "public"."kelas_praktikum" to "authenticated";

grant references on table "public"."kelas_praktikum" to "authenticated";

grant select on table "public"."kelas_praktikum" to "authenticated";

grant trigger on table "public"."kelas_praktikum" to "authenticated";

grant truncate on table "public"."kelas_praktikum" to "authenticated";

grant update on table "public"."kelas_praktikum" to "authenticated";

grant delete on table "public"."kelas_praktikum" to "service_role";

grant insert on table "public"."kelas_praktikum" to "service_role";

grant references on table "public"."kelas_praktikum" to "service_role";

grant select on table "public"."kelas_praktikum" to "service_role";

grant trigger on table "public"."kelas_praktikum" to "service_role";

grant truncate on table "public"."kelas_praktikum" to "service_role";

grant update on table "public"."kelas_praktikum" to "service_role";

grant delete on table "public"."lab" to "anon";

grant insert on table "public"."lab" to "anon";

grant references on table "public"."lab" to "anon";

grant select on table "public"."lab" to "anon";

grant trigger on table "public"."lab" to "anon";

grant truncate on table "public"."lab" to "anon";

grant update on table "public"."lab" to "anon";

grant delete on table "public"."lab" to "authenticated";

grant insert on table "public"."lab" to "authenticated";

grant references on table "public"."lab" to "authenticated";

grant select on table "public"."lab" to "authenticated";

grant trigger on table "public"."lab" to "authenticated";

grant truncate on table "public"."lab" to "authenticated";

grant update on table "public"."lab" to "authenticated";

grant delete on table "public"."lab" to "service_role";

grant insert on table "public"."lab" to "service_role";

grant references on table "public"."lab" to "service_role";

grant select on table "public"."lab" to "service_role";

grant trigger on table "public"."lab" to "service_role";

grant truncate on table "public"."lab" to "service_role";

grant update on table "public"."lab" to "service_role";

grant delete on table "public"."mata_kuliah_praktikum" to "anon";

grant insert on table "public"."mata_kuliah_praktikum" to "anon";

grant references on table "public"."mata_kuliah_praktikum" to "anon";

grant select on table "public"."mata_kuliah_praktikum" to "anon";

grant trigger on table "public"."mata_kuliah_praktikum" to "anon";

grant truncate on table "public"."mata_kuliah_praktikum" to "anon";

grant update on table "public"."mata_kuliah_praktikum" to "anon";

grant delete on table "public"."mata_kuliah_praktikum" to "authenticated";

grant insert on table "public"."mata_kuliah_praktikum" to "authenticated";

grant references on table "public"."mata_kuliah_praktikum" to "authenticated";

grant select on table "public"."mata_kuliah_praktikum" to "authenticated";

grant trigger on table "public"."mata_kuliah_praktikum" to "authenticated";

grant truncate on table "public"."mata_kuliah_praktikum" to "authenticated";

grant update on table "public"."mata_kuliah_praktikum" to "authenticated";

grant delete on table "public"."mata_kuliah_praktikum" to "service_role";

grant insert on table "public"."mata_kuliah_praktikum" to "service_role";

grant references on table "public"."mata_kuliah_praktikum" to "service_role";

grant select on table "public"."mata_kuliah_praktikum" to "service_role";

grant trigger on table "public"."mata_kuliah_praktikum" to "service_role";

grant truncate on table "public"."mata_kuliah_praktikum" to "service_role";

grant update on table "public"."mata_kuliah_praktikum" to "service_role";

grant delete on table "public"."permintaan_sertifikat" to "anon";

grant insert on table "public"."permintaan_sertifikat" to "anon";

grant references on table "public"."permintaan_sertifikat" to "anon";

grant select on table "public"."permintaan_sertifikat" to "anon";

grant trigger on table "public"."permintaan_sertifikat" to "anon";

grant truncate on table "public"."permintaan_sertifikat" to "anon";

grant update on table "public"."permintaan_sertifikat" to "anon";

grant delete on table "public"."permintaan_sertifikat" to "authenticated";

grant insert on table "public"."permintaan_sertifikat" to "authenticated";

grant references on table "public"."permintaan_sertifikat" to "authenticated";

grant select on table "public"."permintaan_sertifikat" to "authenticated";

grant trigger on table "public"."permintaan_sertifikat" to "authenticated";

grant truncate on table "public"."permintaan_sertifikat" to "authenticated";

grant update on table "public"."permintaan_sertifikat" to "authenticated";

grant delete on table "public"."permintaan_sertifikat" to "service_role";

grant insert on table "public"."permintaan_sertifikat" to "service_role";

grant references on table "public"."permintaan_sertifikat" to "service_role";

grant select on table "public"."permintaan_sertifikat" to "service_role";

grant trigger on table "public"."permintaan_sertifikat" to "service_role";

grant truncate on table "public"."permintaan_sertifikat" to "service_role";

grant update on table "public"."permintaan_sertifikat" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."tahun_semester" to "anon";

grant insert on table "public"."tahun_semester" to "anon";

grant references on table "public"."tahun_semester" to "anon";

grant select on table "public"."tahun_semester" to "anon";

grant trigger on table "public"."tahun_semester" to "anon";

grant truncate on table "public"."tahun_semester" to "anon";

grant update on table "public"."tahun_semester" to "anon";

grant delete on table "public"."tahun_semester" to "authenticated";

grant insert on table "public"."tahun_semester" to "authenticated";

grant references on table "public"."tahun_semester" to "authenticated";

grant select on table "public"."tahun_semester" to "authenticated";

grant trigger on table "public"."tahun_semester" to "authenticated";

grant truncate on table "public"."tahun_semester" to "authenticated";

grant update on table "public"."tahun_semester" to "authenticated";

grant delete on table "public"."tahun_semester" to "service_role";

grant insert on table "public"."tahun_semester" to "service_role";

grant references on table "public"."tahun_semester" to "service_role";

grant select on table "public"."tahun_semester" to "service_role";

grant trigger on table "public"."tahun_semester" to "service_role";

grant truncate on table "public"."tahun_semester" to "service_role";

grant update on table "public"."tahun_semester" to "service_role";

grant delete on table "public"."test" to "anon";

grant insert on table "public"."test" to "anon";

grant references on table "public"."test" to "anon";

grant select on table "public"."test" to "anon";

grant trigger on table "public"."test" to "anon";

grant truncate on table "public"."test" to "anon";

grant update on table "public"."test" to "anon";

grant delete on table "public"."test" to "authenticated";

grant insert on table "public"."test" to "authenticated";

grant references on table "public"."test" to "authenticated";

grant select on table "public"."test" to "authenticated";

grant trigger on table "public"."test" to "authenticated";

grant truncate on table "public"."test" to "authenticated";

grant update on table "public"."test" to "authenticated";

grant delete on table "public"."test" to "service_role";

grant insert on table "public"."test" to "service_role";

grant references on table "public"."test" to "service_role";

grant select on table "public"."test" to "service_role";

grant trigger on table "public"."test" to "service_role";

grant truncate on table "public"."test" to "service_role";

grant update on table "public"."test" to "service_role";


